name: docker build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    env:
      IMAGE_NAME: vps_bench:latest
      BUILD_DIR: .

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: AliYun
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_TOKEN }}

      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.BUILD_DIR }}
          file: ./docker/Dockerfile
          push: false
          tags: |
            qiyutech/${{ env.IMAGE_NAME }}

      - name: Run Docker Test
        run: |
          git clone https://github.com/QiYuTechDev/vps_compose
          cd vps_compose && mv -f latest.Dockerfile Dockerfile && docker-compose up
